package envgen

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The aliases file is a second generated artifact living next to env.sh. It
// inherits the whole contract: ownership marker, determinism, atomic writes,
// refusal of foreign files, and round-tripping through a real shell rather
// than a line scan. These tests mirror the env.sh suite on purpose — two
// files with two contracts is how one silently weakens.
func TestAliasesHeaderIsTheOwnershipMarker(t *testing.T) {
	t.Parallel()

	text, err := GenerateAliases([]Tool{{Name: "claude", Strategy: "npm", Aliases: map[string]string{"cc": "claude --dangerously-skip-permissions"}}})
	if err != nil {
		t.Fatalf("GenerateAliases: %v", err)
	}
	for _, want := range []string{"Generated by aes", "DO NOT EDIT", "aes env --write"} {
		if !strings.Contains(string(text), want) {
			t.Errorf("aliases file lacks %q:\n%s", want, text)
		}
	}
	if !strings.HasPrefix(string(text), AliasesHeader) {
		t.Error("aliases file does not start with its own header; a file whose " +
			"marker is not at byte zero fails the ownership check")
	}
}

func TestAliasesGenerateIsDeterministic(t *testing.T) {
	t.Parallel()

	tools := []Tool{
		{Name: "codex", Strategy: "npm", Aliases: map[string]string{"cod": "codex --dangerously-bypass-approvals-and-sandbox"}},
		{Name: "claude", Strategy: "npm", Aliases: map[string]string{"cc": "claude --dangerously-skip-permissions"}},
	}
	a, err := GenerateAliases(tools)
	if err != nil {
		t.Fatalf("generate forward: %v", err)
	}
	b, err := GenerateAliases([]Tool{tools[1], tools[0]})
	if err != nil {
		t.Fatalf("generate reversed: %v", err)
	}
	if string(a) != string(b) {
		t.Errorf("order changed the bytes; generated files must be diffable:\n--- forward ---\n%s\n--- reversed ---\n%s", a, b)
	}
}

func TestAliasesAreSorted(t *testing.T) {
	t.Parallel()

	text, err := GenerateAliases([]Tool{
		{Name: "b", Aliases: map[string]string{"zz": "cmd-z", "aa": "cmd-a"}},
		{Name: "a", Aliases: map[string]string{"mm": "cmd-m"}},
	})
	if err != nil {
		t.Fatalf("GenerateAliases: %v", err)
	}
	lines := strings.Split(strings.TrimSpace(string(text)), "\n")
	var aliases []string
	for _, l := range lines {
		if strings.HasPrefix(l, "alias ") {
			aliases = append(aliases, l)
		}
	}
	if len(aliases) != 3 {
		t.Fatalf("want 3 alias lines, got %d:\n%s", len(aliases), text)
	}
	for i := 1; i < len(aliases); i++ {
		if aliases[i-1] > aliases[i] {
			t.Errorf("alias lines out of order:\n%s", strings.Join(aliases, "\n"))
		}
	}
}

func TestAliasesRoundTripThroughARealShell(t *testing.T) {
	t.Parallel()

	if _, err := exec.LookPath("sh"); err != nil {
		t.Skip("no sh available")
	}

	// A hostile value: spaces, quotes, a command substitution, a semicolon.
	// Sourcing the file decides whether it is an alias, not a line scan.
	home := t.TempDir()
	tools := []Tool{{Name: "demo", Strategy: "github-release", Aliases: map[string]string{
		"cc": `claude --dangerously-skip-permissions`,
	}}}
	path := filepath.Join(home, AliasesFileName)
	if err := WriteAliases(path, tools); err != nil {
		t.Fatalf("WriteAliases: %v", err)
	}

	out, err := exec.Command("sh", "-c", ". "+shellSingle(path)+" && alias cc").Output()
	if err != nil {
		t.Fatalf("sourcing the aliases file: %v", err)
	}
	if !strings.Contains(string(out), "dangerously-skip-permissions") {
		t.Errorf("the alias did not resolve through a real shell: %q", out)
	}
}

func TestAliasesWriteRefusesToClobber(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	path := filepath.Join(home, AliasesFileName)
	const handWritten = "# my aliases\nalias cc='echo mine'\n"
	if err := os.WriteFile(path, []byte(handWritten), 0o644); err != nil {
		t.Fatalf("seed: %v", err)
	}

	err := WriteAliases(path, []Tool{{Name: "claude", Aliases: map[string]string{"cc": "claude"}}})
	if err == nil {
		t.Fatal("WriteAliases overwrote a hand-written file without complaint")
	}
	if !strings.Contains(err.Error(), "refusing to overwrite") {
		t.Errorf("error %q does not say it refused", err)
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if string(after) != handWritten {
		t.Errorf("the file was modified despite the refusal:\n%s", after)
	}
}

func TestAliasesMarkerDoesNotMatchEnvMarker(t *testing.T) {
	t.Parallel()

	// The two markers must be distinct. A check that accepts env.sh's header
	// on aliases.sh would let an unrelated file pass as ours — which is the
	// failure this test exists to prevent.
	if AliasesHeader == Header {
		t.Fatal("AliasesHeader is Header; the two ownership checks are indistinguishable")
	}

	home := t.TempDir()
	path := filepath.Join(home, AliasesFileName)
	// Seed aliases.sh with env.sh's marker: WriteAliases must still refuse.
	if err := os.WriteFile(path, []byte(Header+"\nexport X=1\n"), 0o644); err != nil {
		t.Fatalf("seed: %v", err)
	}
	if err := WriteAliases(path, nil); err == nil {
		t.Error("WriteAliases accepted env.sh's marker on the aliases file")
	}
}

func TestAliasesFileMode(t *testing.T) {
	t.Parallel()

	home := t.TempDir()
	path := filepath.Join(home, AliasesFileName)
	if err := WriteAliases(path, nil); err != nil {
		t.Fatalf("WriteAliases: %v", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if info.Mode().Perm() != FileMode {
		t.Errorf("mode = %o, want %o: a file the user's shell reads must be readable", info.Mode().Perm(), FileMode)
	}
}

func TestEmptyToolsStillWriteAValidFile(t *testing.T) {
	t.Parallel()

	if _, err := exec.LookPath("sh"); err != nil {
		t.Skip("no sh available")
	}
	home := t.TempDir()
	path := filepath.Join(home, AliasesFileName)
	if err := WriteAliases(path, nil); err != nil {
		t.Fatalf("WriteAliases: %v", err)
	}
	// Sourcing an empty aliases file must be a no-op, not an error: a user
	// with no alias-declaring tools runs this path every time.
	if out, err := exec.Command("sh", "-c", ". "+shellSingle(path)+" && echo ok").Output(); err != nil {
		t.Fatalf("sourcing an empty aliases file: %v: %s", err, out)
	}
}
