// Package envgen generates ~/.aes/env.sh: the file that makes installed
// tools reachable.
//
// # Why this package is careful
//
// A user's shell broke silently once: their old tool made .zshrc delegate to
// a config directory behind `if [[ -f ]]` with no else branch. The directory
// was deleted, the guard went false, and the shell came up looking NORMAL —
// no theme, no plugins, no prompt config. Nobody noticed for days. So the
// rules here are not stylistic:
//
//   - The header is an ownership marker. env.sh is generated, and a file
//     lacking that header is the user's own work, not ours to overwrite.
//   - Output is deterministic. No timestamps, everything sorted, so two runs
//     diff clean and a regenerated file shows only real changes.
//   - Writes are atomic. A half-written env.sh breaks the shell on next
//     login, which is the worst failure available here.
//   - This package never touches ~/.zshrc or any shell rc. Appending to a
//     user's rc is a separate, explicit opt-in (--link-shell).
//
// # PATH is not just ~/.aes/bin
//
// Different strategies install to different places, and a go-installed tool
// that nobody put on PATH has installed successfully and is not runnable —
// a broken setup wearing a success message. So Generate walks the installed
// tools and adds each strategy's destination. Package managers contribute
// nothing: brew and apt already place their binaries on PATH.
package envgen

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/quangdang46/agents_environment_setup/internal/installer"
	"github.com/quangdang46/agents_environment_setup/internal/manifest"
)

// npmProbeTimeout bounds the "npm prefix -g" lookup. It is a local query, so
// anything slower means npm is not answering and we contribute nothing.
const npmProbeTimeout = 10 * time.Second

// npmBinDir asks npm where its global prefix is, returning "" when it cannot
// be learned. A missing answer must not become a guessed directory.
func npmBinDir() string {
	ctx, cancel := context.WithTimeout(context.Background(), npmProbeTimeout)
	defer cancel()
	return installer.NPMBinDir(ctx, nil)
}

// Header is the ownership marker. Its presence is what makes a file ours to
// rewrite; its absence is a refusal, not an oversight.
const Header = "# Generated by aes -- DO NOT EDIT BY HAND\n" +
	"# Regenerate with: aes env --write\n"

// FileMode is the mode of a generated env.sh. It is read by the shell and
// nothing else, so it does not need to be private.
const FileMode = 0o644

// DirMode is the mode of the directory holding env.sh.
const DirMode = 0o755

// ErrNotGenerated reports a pre-existing file that env.sh will not overwrite.
var ErrNotGenerated = errors.New("file not generated by aes")

// Tool is one installed tool, as far as the environment is concerned: its
// name, the strategy that installed it, and any variables it contributes.
type Tool struct {
	// Name identifies the tool. It breaks ties when two tools set the same
	// variable, so it must be stable.
	Name string
	// Strategy selects the destination directory. See manifest strategy names.
	Strategy string
	// Vars are environment entries this tool contributes. Optional: most
	// tools contribute none, and the MVP catalog sets no variables at all.
	Vars map[string]string
}

// destinationFor maps a strategy to the directory its binaries land in, and
// reports whether that strategy contributes anything to PATH at all.
//
// It is a variable so tests can supply destinations without depending on
// what the machine running them has installed. Production wiring is
// defaultDestination.
var destinationFor = defaultDestination

// aesBinDir is the directory AES always owns: release binaries land here
// regardless of which strategy fetched them.
func aesBinDir(home string) string { return filepath.Join(home, ".aes", "bin") }

func defaultDestination(strategy, home string) (string, bool) {
	switch strategy {
	case manifest.StrategyGithubRelease:
		// AES owns this one; it is always on PATH.
		return aesBinDir(home), true
	case manifest.StrategyGo:
		return installer.GoBinDir(), true
	case manifest.StrategyCargo:
		return installer.CargoBinDir(), true
	case manifest.StrategyUV:
		return installer.UVBinDir(), true
	case manifest.StrategyNPM:
		// npm's global prefix has no fixed location and can only be learned
		// by asking npm. An empty answer contributes nothing rather than a
		// guess — a wrong directory on PATH is worse than a missing one.
		if dir := npmBinDir(); dir != "" {
			return dir, true
		}
		return "", false
	default:
		// brew and apt already place their binaries on PATH, and any
		// strategy we do not recognise contributes nothing rather than
		// inventing a directory.
		return "", false
	}
}

// Generate renders env.sh for the given installed tools.
//
// The output depends only on its inputs: the same tools and home always
// produce the same bytes, regardless of the order the tools arrive in.
func Generate(tools []Tool, home string) ([]byte, error) {
	if home == "" {
		return nil, fmt.Errorf("envgen: home directory is required")
	}

	dirs := pathEntries(tools, home)
	vars := variableEntries(tools)

	var b bytes.Buffer
	b.WriteString(Header)
	b.WriteString("\n")
	fmt.Fprintf(&b, "export AES_HOME=%s\n", shellQuote(filepath.Join(home, ".aes")))

	if len(vars) > 0 {
		b.WriteString("\n")
		for _, v := range vars {
			fmt.Fprintf(&b, "export %s=%s\n", v.name, shellQuote(v.value))
		}
	}

	if len(dirs) > 0 {
		b.WriteString("\n# PATH entries for installed tools. Each append is guarded, so\n")
		b.WriteString("# sourcing this file twice changes nothing.\n")
		for _, dir := range dirs {
			q := shellQuote(dir)
			b.WriteString("case \":$PATH:\" in\n")
			fmt.Fprintf(&b, "  *:%s:*) ;;\n", q)
			fmt.Fprintf(&b, "  *) PATH=%s:\"$PATH\" ;;\n", q)
			b.WriteString("esac\n")
		}
		b.WriteString("export PATH\n")
	}
	return b.Bytes(), nil
}

// pathEntries returns the deduplicated, sorted destination directories for
// the given tools.
//
// Deduplication matters because several tools commonly share a strategy, and
// a PATH with the same directory three times is noise. Sorting is what makes
// the output byte-identical across runs.
func pathEntries(tools []Tool, home string) []string {
	seen := make(map[string]bool, len(tools))
	dirs := make([]string, 0, len(tools))
	for _, t := range tools {
		dir, ok := destinationFor(t.Strategy, home)
		if !ok || dir == "" || seen[dir] {
			continue
		}
		seen[dir] = true
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)
	return dirs
}

// varEntry is one exported variable.
type varEntry struct {
	name  string
	value string
}

// variableEntries collects variables across tools, deduplicated by name.
//
// When two tools set the same variable the winner is decided by sorted tool
// name, never by map iteration order: the same inputs must always produce the
// same file, and "last one wins" over a map is exactly the nondeterminism
// that makes a generated file churn.
func variableEntries(tools []Tool) []varEntry {
	ordered := make([]Tool, len(tools))
	copy(ordered, tools)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Name < ordered[j].Name })

	seen := make(map[string]bool)
	out := make([]varEntry, 0, len(tools))
	for _, t := range ordered {
		names := make([]string, 0, len(t.Vars))
		for name := range t.Vars {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			if seen[name] {
				continue // an earlier tool won; first by sorted name
			}
			seen[name] = true
			out = append(out, varEntry{name: name, value: t.Vars[name]})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

// shellQuote renders s as a single-quoted POSIX shell word.
//
// Single quotes suppress every expansion, which is exactly what is wanted:
// a path containing $ or a space must reach PATH literally. The only character
// needing care is the quote itself, and the standard '\” form round-trips
// it. Newlines are safe inside single quotes, so a value cannot break out of
// the generated file.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Write renders env.sh and writes it to path atomically.
//
// A pre-existing file that lacks the ownership header is left byte-identical
// and the write is refused: it is the user's own file, and silently
// replacing someone's hand-written environment is not a recovery.
func Write(path string, tools []Tool, home string) error {
	if err := checkOwnership(path); err != nil {
		return err
	}

	content, err := Generate(tools, home)
	if err != nil {
		return err
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, DirMode); err != nil {
		return fmt.Errorf("envgen: create %s: %w", dir, err)
	}

	// The temp file is in the same directory so the rename is atomic: a
	// cross-device move would be a copy, and a crash mid-copy leaves a
	// truncated env.sh that breaks the shell on next login.
	tmp, err := os.CreateTemp(dir, ".env.sh.*.tmp")
	if err != nil {
		return fmt.Errorf("envgen: create temp file: %w", err)
	}
	tmpName := tmp.Name()
	// Cleanup runs on every path, so a failure never leaves a stray temp
	// file next to the user's environment.
	defer func() {
		tmp.Close()
		os.Remove(tmpName)
	}()

	if _, err := tmp.Write(content); err != nil {
		return fmt.Errorf("envgen: write %s: %w", tmpName, err)
	}
	// Chmod explicitly: CreateTemp makes 0600, and a file the user's shell
	// reads should be readable.
	if err := tmp.Chmod(FileMode); err != nil {
		return fmt.Errorf("envgen: chmod %s: %w", tmpName, err)
	}
	if err := tmp.Sync(); err != nil {
		return fmt.Errorf("envgen: sync %s: %w", tmpName, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("envgen: close %s: %w", tmpName, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("envgen: install %s: %w", path, err)
	}
	return nil
}

// checkOwnership refuses to touch a file that env.sh did not generate.
func checkOwnership(path string) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // first run
		}
		return fmt.Errorf("envgen: read %s: %w", path, err)
	}
	if !bytes.HasPrefix(existing, []byte(Header)) {
		return fmt.Errorf("envgen: %w: %s has no aes header, refusing to overwrite it", ErrNotGenerated, path)
	}
	return nil
}
