// Package envgen generates ~/.aes/env.sh: the file that makes installed
// tools reachable.
//
// # Why this package is careful
//
// A user's shell broke silently once: their old tool made .zshrc delegate to
// a config directory behind `if [[ -f ]]` with no else branch. The directory
// was deleted, the guard went false, and the shell came up looking NORMAL —
// no theme, no plugins, no prompt config. Nobody noticed for days. So the
// rules here are not stylistic:
//
//   - The header is an ownership marker. env.sh is generated, and a file
//     lacking that header is the user's own work, not ours to overwrite.
//   - Output is deterministic. No timestamps, everything sorted, so two runs
//     diff clean and a regenerated file shows only real changes.
//   - Writes are atomic. A half-written env.sh breaks the shell on next
//     login, which is the worst failure available here.
//   - This package never touches ~/.zshrc or any shell rc. Appending to a
//     user's rc is a separate, explicit opt-in (--link-shell).
//
// # PATH is not just ~/.aes/bin
//
// Different strategies install to different places, and a go-installed tool
// that nobody put on PATH has installed successfully and is not runnable —
// a broken setup wearing a success message. So Generate walks the installed
// tools and adds each strategy's destination. Package managers contribute
// nothing: brew and apt already place their binaries on PATH.
package envgen

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/quangdang46/agents_environment_setup/internal/exec"
	"github.com/quangdang46/agents_environment_setup/internal/installer"
	"github.com/quangdang46/agents_environment_setup/internal/manifest"
)

// npmProbeTimeout bounds the "npm prefix -g" lookup. It is a local query, so
// anything slower means npm is not answering and we contribute nothing.
const npmProbeTimeout = 10 * time.Second

// npmBinDir asks npm where its global prefix is, returning "" when it cannot
// be learned. A missing answer must not become a guessed directory.
func npmBinDir() string {
	ctx, cancel := context.WithTimeout(context.Background(), npmProbeTimeout)
	defer cancel()
	return installer.NPMBinDir(ctx, nil)
}

// Header is the ownership marker. Its presence is what makes a file ours to
// rewrite; its absence is a refusal, not an oversight.
const Header = "# Generated by aes -- DO NOT EDIT BY HAND\n" +
	"# Regenerate with: aes env --write\n"

// FileMode is the mode of a generated env.sh. It is read by the shell and
// nothing else, so it does not need to be private.
const FileMode = 0o644

// DirMode is the mode of the directory holding env.sh.
const DirMode = 0o755

// ErrNotGenerated reports a pre-existing file that env.sh will not overwrite.
var ErrNotGenerated = errors.New("file not generated by aes")

// Tool is one installed tool, as far as the environment is concerned: its
// name, the strategy that installed it, any variables it contributes, and
// any shell shortcuts it declares.
type Tool struct {
	// Name identifies the tool. It breaks ties when two tools set the same
	// variable, so it must be stable.
	Name string
	// Strategy selects the destination directory. See manifest strategy names.
	Strategy string
	// Vars are environment entries this tool contributes. Optional: most
	// tools contribute none, and the MVP catalog sets no variables at all.
	Vars map[string]string
	// Aliases are the shell shortcuts this tool declares, as the FULL
	// command. The manifest validates them; see manifest.Tool.Aliases for why
	// the value is a command and not a name.
	//
	// Optional, and empty for most tools. An empty map contributes nothing,
	// which is what a tool that declares no shortcut must do.
	Aliases map[string]string
}

// AliasesHeader is the ownership marker for the generated aliases file.
//
// It names the file, not just the tool, because the ownership check is a
// prefix match: a marker identical to Header's would accept an env.sh sitting
// at the aliases.sh path, and aes would then overwrite it thinking it was its
// own. Both are regenerated by the same command; they are not the same file.
const AliasesHeader = "# Generated by aes (aliases.sh) -- DO NOT EDIT BY HAND\n" +
	"# Regenerate with: aes env --write\n"

// AliasesFileName is the basename of the generated aliases file. It lives
// directly under AES_HOME, next to env.sh, and env.sh sources it after PATH
// is set — so one `source ~/.aes/env.sh` gives both PATH and aliases.
const AliasesFileName = "aliases.sh"

// GenerateAliases renders the aliases file from resolved tools. Only tools
// whose aliases map is non-empty contribute; a tool with none contributes
// nothing at all.
//
// Sorted by alias name, so the output is byte-identical for identical input
// regardless of the order tools arrive in. No timestamps, for the same
// reason env.sh carries none.
func GenerateAliases(tools []Tool) ([]byte, error) {
	entries := aliasEntries(tools)

	var b bytes.Buffer
	b.WriteString(AliasesHeader)
	b.WriteString("\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "alias %s=%s\n", e.name, shellQuote(e.command))
	}
	return b.Bytes(), nil
}

// aliasEntry is one rendered shortcut.
type aliasEntry struct {
	name    string
	command string
}

// aliasEntries collects every declared shortcut, deduplicated and sorted.
//
// The first tool in sorted-name order wins a contested name, for the same
// reason variableEntries resolves ties that way: map iteration order must
// never decide what lands in a generated file.
func aliasEntries(tools []Tool) []aliasEntry {
	byName := map[string]string{}
	for _, t := range tools {
		for name, command := range t.Aliases {
			if _, taken := byName[name]; !taken {
				byName[name] = command
			}
		}
	}
	names := make([]string, 0, len(byName))
	for name := range byName {
		names = append(names, name)
	}
	sort.Strings(names)
	out := make([]aliasEntry, 0, len(names))
	for _, name := range names {
		out = append(out, aliasEntry{name: name, command: byName[name]})
	}
	return out
}

// It is a variable so tests can supply destinations without depending on
// what the machine running them has installed. Production wiring is
// defaultDestination.
var destinationFor = defaultDestination

// aesBinDir is the directory AES always owns: release binaries land here
// regardless of which strategy fetched them.
// aesBinDir is where github-release tools land: $AES_HOME/bin.
//
// home is AES_HOME, not the user's home directory. Joining ".aes" on here is
// what produced an env.sh naming a directory that did not exist whenever
// AES_HOME was anything other than ~/.aes.
func aesBinDir(home string) string { return filepath.Join(home, "bin") }

func defaultDestination(strategy, home string) (string, bool) {
	switch strategy {
	case manifest.StrategyGithubRelease:
		// AES owns this one; it is always on PATH.
		return aesBinDir(home), true
	case manifest.StrategyGo:
		return installer.GoBinDir(), true
	case manifest.StrategyCargo:
		return installer.CargoBinDir(), true
	case manifest.StrategyUV:
		return installer.UVBinDir(), true
	case manifest.StrategyNPM:
		// npm's global prefix has no fixed location and can only be learned
		// by asking npm. An empty answer contributes nothing rather than a
		// guess — a wrong directory on PATH is worse than a missing one.
		if dir := npmBinDir(); dir != "" {
			return dir, true
		}
		return "", false
	default:
		// brew and apt already place their binaries on PATH, and any
		// strategy we do not recognise contributes nothing rather than
		// inventing a directory.
		return "", false
	}
}

// Generate renders env.sh for the given installed tools.
//
// home is AES_HOME — the directory aes installed into — not the user's home
// directory. Those coincide only in the default case, and treating them as the
// same value makes the generated file wrong for anyone who points AES_HOME
// somewhere else: it would describe a directory that was never created, and
// sourcing it would move the shell's AES_HOME off the real installation.
//
// The output depends only on its inputs: the same tools and home always
// produce the same bytes, regardless of the order the tools arrive in.
func Generate(tools []Tool, home string) ([]byte, error) {
	if home == "" {
		return nil, fmt.Errorf("envgen: AES_HOME is required")
	}

	dirs := pathEntries(tools, home)
	vars := variableEntries(tools)

	var b bytes.Buffer
	b.WriteString(Header)
	b.WriteString("\n")
	fmt.Fprintf(&b, "export AES_HOME=%s\n", shellQuote(home))

	if len(vars) > 0 {
		b.WriteString("\n")
		for _, v := range vars {
			fmt.Fprintf(&b, "export %s=%s\n", v.name, shellQuote(v.value))
		}
	}

	if len(dirs) > 0 {
		b.WriteString("\n# PATH entries for installed tools. Each append is guarded, so\n")
		b.WriteString("# sourcing this file twice changes nothing.\n")
		for _, dir := range dirs {
			q := shellQuote(dir)
			b.WriteString("case \":$PATH:\" in\n")
			fmt.Fprintf(&b, "  *:%s:*) ;;\n", q)
			fmt.Fprintf(&b, "  *) PATH=%s:\"$PATH\" ;;\n", q)
			b.WriteString("esac\n")
		}
		b.WriteString("export PATH\n")
	}

	// Aliases ride along in env.sh, so one `source ~/.aes/env.sh` gives both
	// PATH and the tool's shell shortcuts. They are not inlined here: the
	// aliases file is separately owned, separately regenerated, and refused
	// if foreign, and inlining it would give a stale copy of something the
	// ownership check otherwise protects.
	aliasesPath := filepath.Join(home, AliasesFileName)
	b.WriteString("\n# Shell shortcuts declared by installed tools. Guarded, so\n")
	b.WriteString("# a missing or unreadable file leaves the shell working.\n")
	q := shellQuote(aliasesPath)
	b.WriteString("[ -f " + q + " ] && . " + q + "\n")
	return b.Bytes(), nil
}

// pathEntries returns the deduplicated, sorted destination directories for
// the given tools.
//
// Deduplication matters because several tools commonly share a strategy, and
// a PATH with the same directory three times is noise. Sorting is what makes
// the output byte-identical across runs.
func pathEntries(tools []Tool, home string) []string {
	seen := make(map[string]bool, len(tools))
	dirs := make([]string, 0, len(tools))
	for _, t := range tools {
		dir, ok := destinationFor(t.Strategy, home)
		if !ok || dir == "" || seen[dir] {
			continue
		}
		seen[dir] = true
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)
	return dirs
}

// varEntry is one exported variable.
type varEntry struct {
	name  string
	value string
}

// variableEntries collects variables across tools, deduplicated by name.
//
// When two tools set the same variable the winner is decided by sorted tool
// name, never by map iteration order: the same inputs must always produce the
// same file, and "last one wins" over a map is exactly the nondeterminism
// that makes a generated file churn.
func variableEntries(tools []Tool) []varEntry {
	ordered := make([]Tool, len(tools))
	copy(ordered, tools)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Name < ordered[j].Name })

	seen := make(map[string]bool)
	out := make([]varEntry, 0, len(tools))
	for _, t := range ordered {
		names := make([]string, 0, len(t.Vars))
		for name := range t.Vars {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			if seen[name] {
				continue // an earlier tool won; first by sorted name
			}
			seen[name] = true
			out = append(out, varEntry{name: name, value: t.Vars[name]})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

// shellQuote renders s as a single-quoted POSIX shell word.
//
// Single quotes suppress every expansion, which is exactly what is wanted:
// a path containing $ or a space must reach PATH literally. The only character
// needing care is the quote itself, and the standard '\” form round-trips
// it. Newlines are safe inside single quotes, so a value cannot break out of
// the generated file.
// shellQuote delegates to exec.ShellQuote. It was a byte-identical copy in
// three packages, and a quoting fix applied to one would have left the other
// two generating differently-quoted shell that consumes the same env.sh and
// PATH values.
func shellQuote(s string) string { return exec.ShellQuote(s) }

// Write renders env.sh and writes it to path atomically.
//
// A pre-existing file that lacks the ownership header is left byte-identical
// and the write is refused: it is the user's own file, and silently
// replacing someone's hand-written environment is not a recovery.
func Write(path string, tools []Tool, home string) error {
	content, err := Generate(tools, home)
	if err != nil {
		return err
	}
	return writeGenerated(path, []byte(Header), content, ".env.sh.*.tmp")
}

// WriteAliases renders the aliases file and writes it to path atomically,
// using the same ownership and atomicity contract as Write.
//
// A pre-existing file lacking AliasesHeader is refused byte-identical: it
// is the user's own alias file, and silently replacing a hand-written one
// is not a recovery.
func WriteAliases(path string, tools []Tool) error {
	content, err := GenerateAliases(tools)
	if err != nil {
		return err
	}
	return writeGenerated(path, []byte(AliasesHeader), content, ".aliases.sh.*.tmp")
}

// writeGenerated is the single implementation both generated files share.
// The ownership marker differs per file, and that is the whole point of the
// parameter: a check that accepts env.sh's marker on aliases.sh would let an
// unrelated file pass as ours.
func writeGenerated(path string, header, content []byte, tmpPattern string) error {
	if err := checkOwnershipFor(path, header); err != nil {
		return err
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, DirMode); err != nil {
		return fmt.Errorf("envgen: create %s: %w", dir, err)
	}

	// The temp file is in the same directory so the rename is atomic: a
	// cross-device move would be a copy, and a crash mid-copy leaves a
	// truncated generated file that breaks the shell on next login.
	tmp, err := os.CreateTemp(dir, tmpPattern)
	if err != nil {
		return fmt.Errorf("envgen: create temp file: %w", err)
	}
	tmpName := tmp.Name()
	// Cleanup runs on every path, so a failure never leaves a stray temp
	// file next to the user's environment.
	defer func() {
		tmp.Close()
		os.Remove(tmpName)
	}()

	if _, err := tmp.Write(content); err != nil {
		return fmt.Errorf("envgen: write %s: %w", tmpName, err)
	}
	// Chmod explicitly: CreateTemp makes 0600, and a file the user's shell
	// reads should be readable.
	if err := tmp.Chmod(FileMode); err != nil {
		return fmt.Errorf("envgen: chmod %s: %w", tmpName, err)
	}
	if err := tmp.Sync(); err != nil {
		return fmt.Errorf("envgen: sync %s: %w", tmpName, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("envgen: close %s: %w", tmpName, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("envgen: install %s: %w", path, err)
	}
	return nil
}

// checkOwnership refuses to touch a file that env.sh did not generate.
func checkOwnership(path string) error {
	return checkOwnershipFor(path, []byte(Header))
}

// checkOwnershipFor is checkOwnership with the marker as a parameter. The
// marker must travel with the file it guards: a check that accepts env.sh's
// marker on aliases.sh would overwrite a file it never generated. Reducing
// this to a boolean ("generated or not") would lose exactly the information
// the refusal depends on.
func checkOwnershipFor(path string, header []byte) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // first run
		}
		return fmt.Errorf("envgen: read %s: %w", path, err)
	}
	if !bytes.HasPrefix(existing, header) {
		return fmt.Errorf("envgen: %w: %s has no aes header, refusing to overwrite it", ErrNotGenerated, path)
	}
	return nil
}
